extends: airbnb-base

env:
  node:   true
  es6:    true
  mocha:  true

plugins:
  - mocha

rules:
  prefer-arrow-callback:
    - 0
  import/no-unresolved:
    - 2
    - ignore:
      - "^~"
      - "^@"
  import/extensions:
    - 0
  import/no-extraneous-dependencies:
    - 0
  import/prefer-default-export:
    - 0
  mocha/no-exclusive-tests:
    - error
  arrow-parens:
    - 2
    - always
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxEOF: 0
  no-return-assign:     0
  no-use-before-define: off
  comma-dangle:
    - error
    - never
  max-len:
    - 2
    - code: 150
